# @format
version: "3.2"

services:
  postgres:
    image: postgres:16.3
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "${POSTGRES_PORT}:5432"
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: uvicorn --reload main:app --host 0.0.0.0
    platform: linux/amd64

volumes:
  postgres_data: