"""'Init'

Revision ID: 033328f6fd57
Revises: 
Create Date: 2024-05-15 12:11:52.067714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033328f6fd57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
 
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###