"""delete tg_id

Revision ID: 27ce1ada47cb
Revises: cb91ec282b37
Create Date: 2024-06-17 13:11:33.745547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ce1ada47cb'
down_revision: Union[str, None] = 'cb91ec282b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_tg_id_key', 'users', type_='unique')
    op.drop_column('users', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_tg_id_key', 'users', ['tg_id'])
    # ### end Alembic commands ###
