"""add auth table

Revision ID: 7e10e656cdcd
Revises: d275b6b12635
Create Date: 2024-06-26 17:30:58.470863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e10e656cdcd'
down_revision: Union[str, None] = 'd275b6b12635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('tg_id', sa.Integer(), nullable=False))
    op.drop_constraint('users_chat_id_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['tg_id'])
    op.drop_column('users', 'chat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('chat_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_chat_id_key', 'users', ['chat_id'])
    op.drop_column('users', 'tg_id')
    op.drop_table('auth')
    # ### end Alembic commands ###
