"""Add created_at and updated_at to Base, create Referral table

Revision ID: 838e2934ef43
Revises: 4d8bc04dc613
Create Date: 2024-05-22 22:14:42.632017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838e2934ef43'
down_revision: Union[str, None] = '4d8bc04dc613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
