"""add name

Revision ID: cb91ec282b37
Revises: 6e1850b5a51a
Create Date: 2024-06-17 13:07:59.476946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb91ec282b37'
down_revision: Union[str, None] = '6e1850b5a51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=50), nullable=False))
    op.drop_constraint('users_chat_id_fkey', 'users', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('users_chat_id_fkey', 'users', 'users', ['chat_id'], ['id'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
