"""empty message

Revision ID: d156b7e6eea5
Revises: 
Create Date: 2024-06-28 18:35:44.155897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd156b7e6eea5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'auth', 'users', ['telegram_id'], ['telegram_id'])
    op.add_column('mining_session', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'mining_session', 'users', ['telegram_id'], ['telegram_id'])
    op.add_column('tasks', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'users', ['telegram_id'], ['telegram_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'telegram_id')
    op.drop_constraint(None, 'mining_session', type_='foreignkey')
    op.drop_column('mining_session', 'telegram_id')
    op.drop_constraint(None, 'auth', type_='foreignkey')
    op.drop_column('auth', 'telegram_id')
    # ### end Alembic commands ###
