"""Change User and Referral models

Revision ID: f6ab84a174b8
Revises: f89ce564e890
Create Date: 2024-05-24 22:00:35.804365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ab84a174b8'
down_revision: Union[str, None] = 'f89ce564e890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referred_id', sa.Integer(), nullable=False))
    op.drop_constraint('referrals_referral_code_key', 'referrals', type_='unique')
    op.create_foreign_key(None, 'referrals', 'users', ['referred_id'], ['id'])
    op.drop_column('referrals', 'referral_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referrals', sa.Column('referral_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_unique_constraint('referrals_referral_code_key', 'referrals', ['referral_code'])
    op.drop_column('referrals', 'referred_id')
    # ### end Alembic commands ###
